/**
 * 扩展图标注册表 —— 仅懒加载页面使用的图标
 *
 * 设计目的：
 * - 将非首屏图标从 Icon.tsx 核心注册表拆分出来，降低首屏 JS 体积
 * - 由各懒加载页面在顶部 import 本模块，Vite 自动提取为共享 chunk
 * - 首屏仅加载 29 个核心图标（~22KB gzip），扩展图标按需加载
 *
 * 使用方式（在懒加载页面顶部）：
 *   import '@/components/ui/icons-extended'
 */
import type { Icon as PhosphorIcon } from '@phosphor-icons/react'
import {
    ArrowsLeftRight,
    Paperclip,
    Shuffle,
    SpeakerHigh,
    CircleNotch,
    Image as ImageIcon,
    Circle,
    Book,
    CaretRight,
    CheckSquare,
    ClipboardText,
    File,
    FileImage,
    GraduationCap,
    GridFour,
    Keyboard,
    MagnifyingGlass,
    PencilSimpleLine,
    SealCheck,
    Table,
    UploadSimple,
    UserCheck,
    ChartBar,
    Microphone,
    ShareNetwork,
    Storefront,
    UserCircle,
    Warning,
    Info,
    XCircle,
    Eye,
    House,
    CaretDown,
    CaretUp,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    ArrowUpRight,
    Copy,
    Quotes,
    PenNib,
    DotsThree,
    Plus,
    Minus,
    FadersHorizontal,
    Calendar,
    Clock,
    Heart,
    Star,
    DownloadSimple,
    Trash,
    PencilSimple,
    ChatCircleDots,
    PaperPlaneTilt,
    Play,
    Pause,
    Stop,
    Lightning,
    FileText,
    Printer,
    Code,
    Scales,
    ArrowSquareOut,
    SpinnerGap,
    Target,
    Compass,
    Trophy,
    Rocket,
    MagicWand,
    PaintBrush,
    Camera,
    Database,
    Tag,
    Bookmark,
    Flag,
    CheckFat,
    ChartLine,
    ChartLineUp,
    Gauge,
    Timer,
    Hourglass,
    Mountains,
    MusicNote,
    IdentificationCard,
    EyeSlash,
    LockKey,
    ChatCircle,
    Command,
    LockSimple,
    UserSwitch,
    NavigationArrow,
    Question,
    Notebook,
    BookBookmark,
    ChalkboardTeacher,
    AddressBook,
    Repeat,
    Stack,
    HandPointing,
    DotsSixVertical,
    Users,
    Sparkle,
    ArrowClockwise,
    PuzzlePiece,
    LinkSimple,
    Student,
    Lightbulb,
    Robot,
    Graph,
} from '@phosphor-icons/react'
import { registerIcons } from './Icon'

/**
 * 扩展图标注册 —— 一次性注入所有非首屏图标
 * 与 Icon.tsx 核心注册表合并，通过 registerIcons 注入 extensionRegistry
 */
registerIcons({
    /* ── 命名别名与遗漏补登记 ──
     * 以下图标名在页面里被实际使用，但从未注册，运行时会渲染成空白
     * 并打印 [Icon] 未注册告警。多数是同一枚图标的另一种叫法
     * （chevron-* ↔ caret-*、search ↔ magnifying-glass、wand ↔ magic-wand），
     * 少数是确实漏登记的独立图标。此处一并补齐。 */
    book: Book,
    'check-square': CheckSquare,
    'chevron-down': CaretDown,
    'chevron-right': CaretRight,
    'chevron-up': CaretUp,
    'clipboard-text': ClipboardText,
    file: File,
    'file-image': FileImage,
    'graduation-cap': GraduationCap,
    grid: GridFour,
    keyboard: Keyboard,
    'paper-plane': PaperPlaneTilt,
    'pencil-line': PencilSimpleLine,
    'pencil-simple-line': PencilSimpleLine,
    'seal-check': SealCheck,
    search: MagnifyingGlass,
    switch: ArrowsLeftRight,
    table: Table,
    upload: UploadSimple,
    'user-check': UserCheck,
    wand: MagicWand,
    'chart-bar': ChartBar,
    'user-circle': UserCircle,
    store: Storefront,
    'share-network': ShareNetwork,
    microphone: Microphone,
    warning: Warning,
    info: Info,
    'x-circle': XCircle,
    eye: Eye,
    house: House,
    'caret-down': CaretDown,
    'caret-up': CaretUp,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'arrow-up-right': ArrowUpRight,
    copy: Copy,
    quotes: Quotes,
    'pen-nib': PenNib,
    'dots-three': DotsThree,
    plus: Plus,
    minus: Minus,
    'faders-horizontal': FadersHorizontal,
    calendar: Calendar,
    clock: Clock,
    heart: Heart,
    star: Star,
    share: ShareNetwork,
    download: DownloadSimple,
    trash: Trash,
    edit: PencilSimple,
    chat: ChatCircleDots,
    send: PaperPlaneTilt,
    play: Play,
    pause: Pause,
    stop: Stop,
    student: Student,
    lightbulb: Lightbulb,
    robot: Robot,
    graph: Graph,
    lightning: Lightning,
    doc: FileText,
    printer: Printer,
    code: Code,
    scale: Scales,
    'arrow-square-out': ArrowSquareOut,
    'spinner-gap': SpinnerGap,
    target: Target,
    compass: Compass,
    trophy: Trophy,
    rocket: Rocket,
    'magic-wand': MagicWand,
    'paint-brush': PaintBrush,
    camera: Camera,
    database: Database,
    tag: Tag,
    bookmark: Bookmark,
    flag: Flag,
    'check-fat': CheckFat,
    'chart-line': ChartLine,
    'chart-line-up': ChartLineUp,
    gauge: Gauge,
    timer: Timer,
    hourglass: Hourglass,
    mountains: Mountains,
    'music-note': MusicNote,
    'identification-card': IdentificationCard,
    'eye-slash': EyeSlash,
    'lock-key': LockKey,
    'chat-circle': ChatCircle,
    command: Command,
    'lock-simple': LockSimple,
    'user-switch': UserSwitch,
    'navigation-arrow': NavigationArrow,
    question: Question,
    notebook: Notebook,
    'book-bookmarks': BookBookmark,
    'chalkboard-teacher': ChalkboardTeacher,
    'address-book': AddressBook,
    repeat: Repeat,
    stack: Stack,
    'hand-pointing': HandPointing,
    'dots-six-vertical': DotsSixVertical,
    users: Users,
    // v5.0 Task 19-20：3 种创新模式 + 4 基础模式扩展图标别名
    // 'sparkles'（复数）作为 'sparkle' 的别名，供 PoemWheelMode/ImageryPuzzleMode/SixLevelImmersiveMode/CollectiveRaceMode 使用
    sparkles: Sparkle,
    // 'bolt' 作为 'lightning' 的别名，供 PoemWheelMode/SpeedPkMode/PoemRelayMode 使用（呼应"闪电抽题/抢答"语义）
    bolt: Lightning,
    // 'refresh' 作为 'arrow-clockwise' 的别名，供多个模式的重置按钮使用
    refresh: ArrowClockwise,
    // 'puzzle-piece' 供 ImageryPuzzleMode 使用
    'puzzle-piece': PuzzlePiece,
    // 'link' 作为 'link-simple' 的别名，供 PoemRelayMode 使用（呼应"接龙链接"语义）
    link: LinkSimple,

    /* ── AI 副驾多模态所需图标 ──
     * 未注册的图标名在运行时只会渲染成空白并打印告警，
     * 按钮看起来就是"少了个图标"——附件、朗读这些入口会直接失去可辨识性。 */
    paperclip: Paperclip,
    // 'shuffle' 用于「已按能力自动改选模型」的提示
    shuffle: Shuffle,
    'speaker-high': SpeakerHigh,
    // 'spinner' 取 CircleNotch：Phosphor 里它才是标准的加载转圈形态
    spinner: CircleNotch,
    image: ImageIcon,
    'file-text': FileText,
    // 'circle' 供家校联系本的活动勾选（未完成态）使用
    circle: Circle,
} as Record<string, PhosphorIcon>)
